Feature/new analyzers
Catel/Catel.Analyzers pull request #266
Opened 2022-11-27 22:05 UTC by Averus-a

### Description of Change ###
Moved new analyzers + refactoring

### Issues Resolved ### 

- fixes #

### API Changes ###

 
None

### Platforms Affected ### 

- All
- WPF
- UWP
- iOS
- Android

### Behavioral Changes ###

None

### Testing Procedure ###

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

2022-11-28 12:12 UTC, GeertvanHorrik requested changes
Please rename all the CL00 to CTL00

2022-11-28 12:12 UTC, GeertvanHorrik commented on src/Catel.Analyzers/Analyzers/ExceptionsAnalyzer.cs
> +            ImmutableArray.Create(Descriptors.CL0011_ProvideCatelLogOnThrowingException);
Use CTL instead of CL

2022-11-28 12:12 UTC, GeertvanHorrik commented on src/Catel.Analyzers.Tests/CTL0008/CTL0008DiagnosticFacts.cs
> +            private static readonly ExpectedDiagnostic ExpectedDiagnostic = ExpectedDiagnostic.Create(Descriptors.CL0008_DoUseThrowIfNullForArgumentCheck);
CTL

2022-11-28 12:12 UTC, GeertvanHorrik commented on src/Catel.Analyzers.Tests/CTL0008/CTL0008DiagnosticFacts.cs
> +                Solution.Verify<ArgumentsAnalyzer>(analyzer => RoslynAssert.NoAnalyzerDiagnostics(analyzer, Descriptors.CL0008_DoUseThrowIfNullForArgumentCheck, before));
CTL

2022-11-28 12:12 UTC, GeertvanHorrik commented on src/Catel.Analyzers.Tests/CTL0011/CTL0011DiagnosticFacts.cs
> +            private static readonly ExpectedDiagnostic ExpectedDiagnostic = ExpectedDiagnostic.Create(Descriptors.CL0011_ProvideCatelLogOnThrowingException);
CTL

2022-11-28 13:42 UTC, Averus-a commented
Updated

2022-11-29 09:40 UTC, GeertvanHorrik requested changes

2022-11-29 09:40 UTC, GeertvanHorrik commented on src/Catel.Analyzers.Tests/Catel.Analyzers.Tests.csproj
> +  <ItemGroup>
please undo this part

2022-11-29 09:40 UTC, GeertvanHorrik commented on src/Catel.Analyzers/AnalyzerReleases.Shipped.md
> +## Release 1.4.3
1.5.0

2022-11-29 11:28 UTC, GeertvanHorrik approved these changes

2022-11-29 11:28 UTC, merged